[package]
name = "backrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.10.0"
dotenv = "0.15.0"
flate2 = "1.0"
tar = "0.4.38"